version: '3'

services:
  web:
    build: .
    command: bash -c "python -m app"
    container_name: tgindex
    volumes:
      - .:/tgindex
    ports:
      - "5666:5666"
    env_file:
      - .env